version: '2.1'
services:
  fakeSDK1:
    image: fake-sdk
    build:
      context: ./fakeSDK
  fakeSDK2:
    image: fake-sdk
  nginx:
    image: nginx:alpine
    volumes: 
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8080:80
  # benchmark:
