openapi: 3.0.0
info:
  title: 多轮场景日誌管理
  description: 多轮场景日志管理 API，包含日志搜寻及日志导出
  version: 1.0.0
  contact:
    name: Frank Chang
    email: frankchang@emotibot.com

servers:
  - url: http://127.0.0.1:8182/api/v1/stats

components:
  ###############################################################################
  #                                   Schemas                                   #
  ###############################################################################
  schemas:
    RequestTERecordsBody:
      type: object
      properties:
        start_time:
          description: 日志搜寻/导出时间段开始时间
          type: integer
        end_time:
          description: 日志搜寻/导出时间段结束时间
          type: integer
        scenario_name:
          description: 筛选项 - 多轮场景名称
          type: string
        platforms:
          description: 筛选项 - 维度 (平台 code)
          type: array
          items:
            type: string
        genders:
          description: 筛选项 - 维度 (性别 code)
          type: array
          items:
            type: string
        uid:
          description: 筛选项 - User ID
          type: string
        feedback:
          description: 筛选项 - 反馈 (有用、无用... etc)
          type: string
    QueryTERecordsBody:
      type: object
      allOf:
        - $ref: '#/components/schemas/RequestTERecordsBody'
        - type: object
          properties:
            page:
              description: 分页页码，从 0 开始，预设为 0
              type: integer
              default: 0
            limit:
              description: 单笔页数，预设为 20
              type: integer
              default: 20
    ExportTERecordsBody:
      type: object
      allOf:
        - $ref: '#/components/schemas/RequestTERecordsBody'

  ################################################################################
  #                                  Parameters                                  #
  ################################################################################
  parameters:
    EnterpriseId:
      name: X-Enterpriseid
      description: 企业 ID
      in: header
      required: true
      schema:
        type: string
    AppId:
      name: X-Appid
      description: 操作的机器人ID
      in: header
      required: true
      schema:
        type: string
    UserId:
      name: X-Userid
      description: 使用者 ID
      in: header
      required: true
      schema:
        type: string
    ExportId:
      name: export_id
      description: 日志导出档案下载 ID
      in: path
      required: true
      schema:
        type: string
    Locale:
      name: locale
      in: header
      description: 回传资料使用语系，预设使用 zh-cn
      required: false
      schema:
        type: string
        enum:
          - zh-cn
          - zh-tw

  ################################################################################
  #                                 Request Bodies                               #
  ################################################################################
  requestBodies:
    QueryTERecords:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/QueryTERecordsBody'
    ExportTERecords:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ExportTERecordsBody'
  
paths:
  /teRecords:
    post:
      tags:
        - Query
      description: 日誌搜尋結果
      parameters:
        - $ref: '#/components/parameters/AppId'
        - $ref: '#/components/parameters/UserId'
      requestBody:
        $ref: '#/components/requestBodies/QueryTERecords'
      responses:
        200:
          description: 日志搜寻结果
          content:
            application/json:
              schema:
                type: object
                properties:
                  tableheader:
                    description: 前台表格显示表格的标头
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          description: 表格标头 ID
                          type: string
                        text:
                          description: 表格标头文字
                          type: string
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        taskengine_session_id:
                          description: 多轮场景会话 ID
                          type: string
                        session_id:
                          description: 会话 ID
                          type: string
                        user_id:
                          description: 用户 ID
                          type: string
                        scenario_id:
                          description: 多轮场景 ID
                          type: string
                        scenario_name:
                          description: 多轮场景名称
                          type: string
                        last_node_id:
                          description: 多轮场景最终结点 ID
                          type: string
                        last_node_name:
                          description: 多轮场景最终节点名称
                          type: string
                        trigger_time:
                          description: 多轮场景触发时间
                          type: string
                        finish_time:
                          description: 多轮场景完成时间
                          type: string
                        feedback:
                          description: 反馈 (有用、无用... etc)
                          type: string
                        custom_feedback:
                          description: 客制化反馈
                          type: string
                        feedback_time:
                          description: 反馈时间
                          type: string
                  limit:
                    description: 单笔页数
                    type: integer
                  page:
                    description: 分页页码
                    type: integer
                  total_sizes:
                    description: 日志总条数
                    type: integer
        400:
          description: Bad request
        500:
          description: Internal server error

  /teRecords/export:
    post:
      tags:
        - Export
      summary: 日志导出
      description: 建立日志导出档案；同一企业同时间只能有一个日志导出任务在进行
      parameters:
        - $ref: '#/components/parameters/EnterpriseId'
        - $ref: '#/components/parameters/AppId'
        - $ref: '#/components/parameters/UserId'
      requestBody:
        $ref: '#/components/requestBodies/ExportTERecords'
      responses:
        200:
          description: 成功建立日志导出任务
          content:
            application/json:
              schema:
                type: object
                properties:
                  export_id:
                    description: 日志导出任务 ID
                    type: string
        403:
          description: 该企业目前已有导出任务在执行，无法再次建立日志导出任务
        500:
          description: Internal server error
  
  /teRecords/export/{export_id}:
    parameters:
      - $ref: '#/components/parameters/EnterpriseId'
      - $ref: '#/components/parameters/AppId'
      - $ref: '#/components/parameters/UserId'
      - $ref: '#/components/parameters/ExportId'
    get:
      tags:
        - Export
      summary: 下载日志导出档案
      description: 下载日志导出档案
      parameters:
        - $ref: '#/components/parameters/EnterpriseId'
        - $ref: '#/components/parameters/AppId'
        - $ref: '#/components/parameters/UserId'
      responses:
        200:
          description: 日志导出档案 (.zip 或 .xlsx 档)
        204:
          description: 日志导出无结果，因此无对应的日志导出档案可下载
        403:
          description: 导出任务仍在执行中，无法下载日志导出档案
        404:
          description: 日志导出任务或日志导出档案不存在
        500:
          description: Internal server error
    delete:
      tags:
        - Export
      summary: 删除日志导出档案
      description: 删除日志导出档案
      parameters:
        - $ref: '#/components/parameters/EnterpriseId'
        - $ref: '#/components/parameters/AppId'
        - $ref: '#/components/parameters/UserId'
      responses:
        200:
          description: 成功删除日志导出档案
        404:
          description: 无相关日志导出档案可删除
        500:
          description: Internal server error

  /teRecords/export/{export_id}/status:
    parameters:
      - $ref: '#/components/parameters/EnterpriseId'
      - $ref: '#/components/parameters/AppId'
      - $ref: '#/components/parameters/UserId'
      - $ref: '#/components/parameters/ExportId'
    get:
      tags:
        - Export
      summary: 查询日志导出任务目前状态
      description: 回传所查询日志导出任务目前状态
      parameters:
        - $ref: '#/components/parameters/EnterpriseId'
        - $ref: '#/components/parameters/AppId'
        - $ref: '#/components/parameters/UserId'
      responses:
        200:
          description: 日志导出任务目前状态
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    description: 日志导出任务目前状态
                    type: string
                    enum:
                      - RUNNING
                      - COMPLETED
                      - FAILED
                      - EMPTY
        404:
          description: 所查询日志导出任务不存在
        500:
          description: Internal server error
