openapi: 3.0.0
info:
  title: 数据优化/统计分析
  description: 统计分析 API
  version: 1.0.0
  contact:
    name: Frank Chang
    email: frankchang@emotibot.com

servers:
  - url: http://127.0.0.1:8182/api/v1/stats

components:
  ###############################################################################
  #                                   Schemas                                   #
  ###############################################################################
  schemas:
    VisitResponseStats:
      type: object
      properties:
        conversations:
          description: 总会话数
          type: integer
        unique_users:
          description: 独立用户数
          type: integer
        new_users:
          description: 新增用户数
          type: integer
        total_asks:
          description: 总提问数
          type: integer
        normal_responses:
          description: 标准回复
          type: integer
        chats:
          description: 聊天
          type: integer
        others:
          description: 其他
          type: integer
        unknown_qna:
          description: 未知问题回覆
          type: integer
        unsolved:
          description: 未解决
          type: integer
        success_rate:
          description: 成功率
          type: string
        solved:
          description: 解决数
          type: integer
        solved_rate:
          description: 解决率
          type: string
        conversation_per_session:
          description: 平均会话对话数
          type: string
    VisitResponseTimeStats:
      type: object
      allOf:
        - type: object
          properties:
            time:
              description: 时间段
              type: integer
            time_txt:
              description: 时间段
              type: string
        - $ref: '#/components/schemas/VisitResponseStats'
    VisitResponseTimeStatsData:
      type: object
      properties:
        data:
          type: object
          properties:
            quantities:
              type: array
              items:
                $ref: '#/components/schemas/VisitResponseTimeStats'
            type:
              description: 时间聚合类型
              type: string
            name:
              description: 提问数
              type: string
    VisitResponseTimeStatsTotal:
      type: object
      allOf:
        - $ref: '#/components/schemas/VisitResponseTimeStats'
    VisitResponseDimensionStatsData:
      type: object
      properties:
        data:
          type: array
          items:
            type: object
            properties:
              q:
                type: object
                allOf:
                  - $ref: '#/components/schemas/VisitResponseStats'
              id:
                description: 维度 ID
                type: string
              name:
                description: 维度名称
                type: string
    VisitResponseDimensionStatsTotal:
      type: object
      allOf:
        - $ref: '#/components/schemas/VisitResponseStats'
    VisitResponseQtypeStatsData:
      type: object
      properties:
        data:
          type: array
          items:
            type: object
            properties:
              q:
                type: object
                allOf:
                  - $ref: '#/components/schemas/VisitResponseStats'
              id:
                description: 问答类别 ID
                type: string
              name:
                description: 问答类别名称
                type: string
    VisitResponseQtypeStatsTotal:
      type: object
      allOf:
        - $ref: '#/components/schemas/VisitResponseStats'
    TopStdQuestions:
      type: object
      properties:
        path:
          type: string
          description: N/A
        q:
          type: integer
          description: 问题总数
        question:
          type: string
          description: 问题
        rank:
          type: integer
          description: 总数排名
    TopUnusedQuestions:
      type: object
      properties:
        first_time:
          type: string
          description: 第一次此问题被发问的时间 (Unix time in string format)
        first_time_text:
          type: string
          description: 第一次此问题被发问的时间 (YYYY-MM-DD HH:mm:ss format)
        last_time:
          type: string
          description: 最后一次此问题被发问的时间 (Unix time in string format)
        last_time_text:
          type: string
          description: 最后一次此问题被发问的时间 (YYYY-MM-DD HH:mm:ss format)
        q:
          type: integer
          description: 问题总数
        question:
          type: string
          description: 问题
        rank:
          type: integer
          description: 总数排名

  ################################################################################
  #                                  Parameters                                  #
  ################################################################################
  parameters:
    Authorization:
      name: Authorization
      description: 使用者連接權杖
      in: header
      required: true
      schema:
        type: string
    EnterpriseId:
      name: X-Enterpriseid
      description: 企业 ID
      in: header
      required: true
      schema:
        type: string
    AppId:
      name: X-Appid
      description: 操作的机器人ID
      in: header
      required: true
      schema:
        type: string
    UserId:
      name: X-Userid
      description: 使用者 ID
      in: header
      required: true
      schema:
        type: string
    StartTime:
      name: t1
      description: 统计时间段开始时间 (YYYYMMDD)
      in: query
      required: true
      schema:
        type: string
    EndTime:
      name: t2
      description: 统计时间段结束时间 (YYYYMMDD)
      in: query
      required: true
      schema:
        type: string
    Category:
      name: category
      description: 统计維度 (只有当 filter = category 的时候生效)
      in: query
      required: true
      schema:
        type: string
        enum:
          - platform
          - sex
    TopN:
      name: top
      description: 欲回传的 Top 'N' 问题数量
      in: query
      schema:
        type: integer
        default: 20
    Locale:
      name: locale
      in: header
      description: 回传资料使用语系，预设使用 zh-cn
      required: false
      schema:
        type: string
        enum:
          - zh-cn
          - zh-tw
  
paths:
  /visit?type=time:
    post:
      tags:
        - Statistic
      summary: 日志统计分析 (访问数据统计(时间))
      description: 日志统计分析结果
      parameters:
        - $ref: '#/components/parameters/Authorization'
        - $ref: '#/components/parameters/AppId'
        - $ref: '#/components/parameters/UserId'
        - $ref: '#/components/parameters/StartTime'
        - $ref: '#/components/parameters/EndTime'
      responses:
        200:
          description: 日志统计分析结果
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/VisitResponseTimeStatsData'
                type: object
                properties:
                  table_header:
                    description: 前台表格显示表格的标头
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          description: 表格标头 ID
                          type: string
                        text:
                          description: 表格标头文字
                          type: string
                  total:
                    type: object
                    allOf:
                      - $ref: '#/components/schemas/VisitResponseTimeStatsTotal'
        400:
          description: Bad request
        401:
          description: Unauthorized
        500:
          description: Internal server error

  /visit?type=barchart&filter=category:
    post:
      tags:
        - Statistic
      summary: 日志统计分析 (访问数据统计(维度))
      description: 日志统计分析结果
      parameters:
        - $ref: '#/components/parameters/Authorization'
        - $ref: '#/components/parameters/AppId'
        - $ref: '#/components/parameters/UserId'
        - $ref: '#/components/parameters/StartTime'
        - $ref: '#/components/parameters/EndTime'
        - $ref: '#/components/parameters/Category'
      responses:
        200:
          description: 日志统计分析结果
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/VisitResponseDimensionStatsData'
                type: object
                properties:
                  table_header:
                    description: 前台表格显示表格的标头
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          description: 表格标头 ID
                          type: string
                        text:
                          description: 表格标头文字
                          type: string
                  total:
                    type: object
                    allOf:
                      - $ref: '#/components/schemas/VisitResponseDimensionStatsTotal'
        400:
          description: Bad request
        401:
          description: Unauthorized
        500:
          description: Internal server error
 
  /visit?type=barchart&filter=qtype:
    post:
      tags:
        - Statistic
      summary: 日志统计分析 (问答类别统计)
      description: 日志统计分析结果
      parameters:
        - $ref: '#/components/parameters/Authorization'
        - $ref: '#/components/parameters/AppId'
        - $ref: '#/components/parameters/UserId'
        - $ref: '#/components/parameters/StartTime'
        - $ref: '#/components/parameters/EndTime'
      responses:
        200:
          description: 日志统计分析结果
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/VisitResponseQtypeStatsData'
                type: object
                properties:
                  table_header:
                    description: 前台表格显示表格的标头
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          description: 表格标头 ID
                          type: string
                        text:
                          description: 表格标头文字
                          type: string
                  total:
                    type: object
                    allOf:
                      - $ref: '#/components/schemas/VisitResponseQtypeStatsTotal'
        400:
          description: Bad request
        401:
          description: Unauthorized
        500:
          description: Internal server error
  
  /question?type=top:
    get:
      tags:
        - Statistic
      summary: 熱點問題 Top N
      description: Top N 熱點問題
      parameters:
        - $ref: '#/components/parameters/Authorization'
        - $ref: '#/components/parameters/AppId'
        - $ref: '#/components/parameters/UserId'
        - $ref: '#/components/parameters/StartTime'
        - $ref: '#/components/parameters/EndTime'
        - $ref: '#/components/parameters/TopN'
      responses:
        200:
          description: Top N 热点问题结果
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TopStdQuestions'
        400:
          description: Bad request
        401:
          description: Unauthorized
        500:
          description: Internal server error

  /question?type=unused:
    get:
      tags:
        - Statistic
      summary: 未匹配问题 Top N
      description: Top N 未匹配問題
      parameters:
        - $ref: '#/components/parameters/Authorization'
        - $ref: '#/components/parameters/AppId'
        - $ref: '#/components/parameters/UserId'
        - $ref: '#/components/parameters/StartTime'
        - $ref: '#/components/parameters/EndTime'
        - $ref: '#/components/parameters/TopN'
      responses:
        200:
          description: Top N 未匹配问题结果
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TopUnusedQuestions'
        400:
          description: Bad request
        401:
          description: Unauthorized
        500:
          description: Internal server error
