ARG baseImageName
FROM ${baseImageName}
RUN go get github.com/go-sql-driver/mysql
RUN go get github.com/kataras/iris
RUN go get github.com/kataras/golog
RUN go get github.com/kataras/pio
RUN go get github.com/tealeg/xlsx
RUN go get github.com/hashicorp/go-version
RUN go get github.com/hashicorp/consul/api
RUN go get github.com/bitly/go-simplejson
RUN go get github.com/gonum/blas
RUN go get github.com/gonum/internal/asm/f32
RUN go get github.com/gonum/internal/asm/f64
RUN go get github.com/gorilla/mux
RUN go get github.com/dgrijalva/jwt-go
RUN go get github.com/siongui/gojianfan
RUN go get github.com/satori/go.uuid
