FROM docker-reg.emotibot.com.cn:55688/base/sles12sp3:2.0.2

RUN zypper ar http://download.opensuse.org/tumbleweed/repo/oss/ oss \
    && zypper --gpg-auto-import-keys ref \
    && zypper -n in --force-resolution \
        unzip \
        wget \
        vim \
        curl \
        glibc-locale \
        go1.9 \
        git \
    && rm -rf /var/lib/apt/lists/*

RUN go get github.com/go-sql-driver/mysql 
RUN go get github.com/kataras/iris
RUN go get github.com/kataras/golog
RUN go get github.com/kataras/pio
RUN go get github.com/tealeg/xlsx
RUN go get github.com/hashicorp/go-version
RUN go get github.com/hashicorp/consul
RUN go get github.com/bitly/go-simplejson
RUN go get github.com/gonum/blas
RUN go get github.com/gonum/internal/asm/f32
RUN go get github.com/gonum/internal/asm/f64
RUN go get github.com/gorilla/mux
RUN go get github.com/dgrijalva/jwt-go

ENV LANG C.UTF-8
