version: '3'

services:
  openapi-adapter:
    image: ${OPENAPI_ADAPTER_IMAGE_NAME}
    container_name: ${OPENAPI_ADAPTER_CONTAINER_NAME}
    ports:
      - ${OPENAPI_ADAPTER_PORT}:8080/tcp
    environment:
      # - port openapi adapter running in docker
      - OPENAPI_ADAPTER_SERVER_PORT=8080
      # - openapi (controller) host url
      - OPENAPI_ADAPTER_EC_HOST=http://${EC_HOST}:${EC_PORT}
    logging:
      driver: json-file
      options:
        max-file: '10'
        max-size: 5M
    restart: always
