version: '2'
services:
    rabbitmq:
        image: rabbitmq:3
        hostname: "my-rabbit"
        container_name: "rabbitmq"
        ports:
            - '5672:5672' 
        mem_limit: 5125m
        volumes:
            - ${RABBITMQ_DATA_PATH}:/var/lib/rabbitmq
            - /etc/localtime:/etc/localtime
        restart: always
