/*
 * 机器人设置API
 * This is api document page for robot setting RestAPIs
 *
 * OpenAPI spec version: 1.0.0
 * Contact: danielwu@emotibot.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.FunctionInfo;
import java.io.IOException;

/**
 * Function
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.java.JavaClientCodegen", date = "2018-03-01T18:34:36.180+08:00")
public class Function {
@SerializedName("FUNC_NAME")
  private FunctionInfo FUNC_NAME = null;
  
  public Function FUNC_NAME(FunctionInfo FUNC_NAME) {
    this.FUNC_NAME = FUNC_NAME;
    return this;
  }

  
  /**
  * Get FUNC_NAME
  * @return FUNC_NAME
  **/
  @ApiModelProperty(value = "")
  public FunctionInfo getFUNCNAME() {
    return FUNC_NAME;
  }
  public void setFUNCNAME(FunctionInfo FUNC_NAME) {
    this.FUNC_NAME = FUNC_NAME;
  }
  
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Function function = (Function) o;
    return Objects.equals(this.FUNC_NAME, function.FUNC_NAME);
  }

  @Override
  public int hashCode() {
    return Objects.hash(FUNC_NAME);
  }
  
  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Function {\n");
    
    sb.append("    FUNC_NAME: ").append(toIndentedString(FUNC_NAME)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  
}



