/*
 * 机器人设置API
 * This is api document page for robot setting RestAPIs
 *
 * OpenAPI spec version: 1.0.0
 * Contact: danielwu@emotibot.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.Qa;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * Qas
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.java.JavaClientCodegen", date = "2018-03-01T18:34:36.180+08:00")
public class Qas {
@SerializedName("count")
  private Integer count = null;
  @SerializedName("qa_infos")
  private List<Qa> qaInfos = null;
  
  public Qas count(Integer count) {
    this.count = count;
    return this;
  }

  
  /**
  * 全部的 qa 数量
  * @return count
  **/
  @ApiModelProperty(value = "全部的 qa 数量")
  public Integer getCount() {
    return count;
  }
  public void setCount(Integer count) {
    this.count = count;
  }
  
  public Qas qaInfos(List<Qa> qaInfos) {
    this.qaInfos = qaInfos;
    return this;
  }

  public Qas addQaInfosItem(Qa qaInfosItem) {
    
    if (this.qaInfos == null) {
      this.qaInfos = new ArrayList<Qa>();
    }
    
    this.qaInfos.add(qaInfosItem);
    return this;
  }
  
  /**
  * Get qaInfos
  * @return qaInfos
  **/
  @ApiModelProperty(value = "")
  public List<Qa> getQaInfos() {
    return qaInfos;
  }
  public void setQaInfos(List<Qa> qaInfos) {
    this.qaInfos = qaInfos;
  }
  
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Qas qas = (Qas) o;
    return Objects.equals(this.count, qas.count) &&
        Objects.equals(this.qaInfos, qas.qaInfos);
  }

  @Override
  public int hashCode() {
    return Objects.hash(count, qaInfos);
  }
  
  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Qas {\n");
    
    sb.append("    count: ").append(toIndentedString(count)).append("\n");
    sb.append("    qaInfos: ").append(toIndentedString(qaInfos)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  
}



