FROM docker-reg.emotibot.com.cn:55688/base/sles12sp3-golang1.9:20180416 AS build-env
ENV GOPATH /go/
ARG PROJECT

COPY . /go/src/emotibot.com/emotigo/module

RUN cd /go/src/emotibot.com/emotigo/module/${PROJECT} && go get -v && go install

FROM docker-reg.emotibot.com.cn:55688/base/sles12sp3:2.0.2
RUN zypper ar http://download.opensuse.org/distribution/leap/42.3/repo/oss/ oss \
       && zypper --gpg-auto-import-keys ref \
       && zypper -n in --force-resolution \
          glibc-locale 

ENV LANG C.UTF-8


ARG PROJECT
ENV GOPATH /go
COPY --from=build-env /go/bin/admin-api /usr/local/bin/admin-api

WORKDIR /usr/local/bin
COPY ${PROJECT}/docker/entrypoint.sh entrypoint.sh
COPY ${PROJECT}/docker/env.template env.template
COPY ${PROJECT}/docker/files_init.sh files_init.sh
COPY ${PROJECT}/docker/profile_rebuild.sh profile_rebuild.sh
COPY ${PROJECT}/InitFiles InitFiles
CMD ["./entrypoint.sh", "env.template"]
