# close_inactive: 1m, close watch fd after 1m
# ignore_older: 2m, modification time 2m older than now will be ignore 
# clean_inactive: 5m, clean /data/registry if timestamp diff more than 5m
# ref: https://www.elastic.co/guide/en/beats/filebeat/current/configuration-filebeat-options.html
filebeat.prospectors:
- input_type: log
  paths:
    - /var/logs/filebeat/*/*/*/*/*.log
  scan_frequency: 30s
  close_inactive: 1m
  ignore_older: 2m
  clean_inactive: 5m
output.logstash:
  hosts: ["vca-logstash.api.vip.com:5043"]
output.console:
  pretty: true
output.file:
  enabled: true
  path: "/tmp/filebeat"
  rotate_every_kb: 10000
  number_of_files: 7

# Logging
logging.to_files: true
logging.level: debug
logging.files:
  path: /var/log/filebeat
  name: filebeat.log
  keepfiles: 7
