/*
 * 机器人设置API
 * This is api document page for robot setting RestAPIs
 *
 * OpenAPI spec version: 1.0.0
 * Contact: danielwu@emotibot.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.Componentsschemasfunction;

import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for 机器人技能Api
 */
@Ignore
public class 机器人技能ApiTest {

    private final 机器人技能Api api = new 机器人技能Api();

    
    /**
     * 取得所有机器人技能开关状态
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void functionsGetTest() throws ApiException {
        
        Componentsschemasfunction response = api.functionsGet();

        // TODO: test validations
    }
    
}
