version: '2'
services:
    mysql:
        image: mysql:5.7 
        container_name: mysql
        ports:
            - "${MYSQL_MAIN_PORT}:${MYSQL_MAIN_PORT}"
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_MAIN_PASS} 
        mem_limit: 5125m
        volumes:
            - ../mysql/my.cnf:/etc/mysql/my.cnf
            - ../mysql/backend_log.sql:/var/local/database/backend_log.sql
            - ../mysql/docker-entrypoint.sh:/usr/local/bin/docker-entrypoint.sh
            - ${DB_DATA_PATH}:/var/lib/mysql
            - /etc/localtime:/etc/localtime
        restart: always
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        ports:
            - '3380:80'
        mem_limit: 5125m
        environment:
            MYSQL_USERNAME: ${MYSQL_MAIN_USER}
            MYSQL_PASSWORD: ${MYSQL_MAIN_PASS}
        volumes:
            - /etc/localtime:/etc/localtime
        links:
            - mysql:db
        restart: always
        depends_on:
            - "mysql"
    mongo:
        image: mongo:3.2.8
        container_name: logging-mongo
        ports:
            - "${MONGO_MAIN_PORT}:${MONGO_MAIN_PORT}"
        volumes:
            - $MONGO_DATA_PATH/db:/data/db
            - $MONGO_DATA_PATH/configdb:/data/configdb
            - /etc/localtime:/etc/localtime
            - ../mongo/init_users.js:/tmp/init_users.js
        restart: always
        command: mongod ${MONGO_AUTH}
