FROM golang:1.8-alpine AS buildEnv

WORKDIR /go/src/fakeSDK
ADD ./ /go/src/fakeSDK
RUN go build -o fakeSDK

FROM alpine:3.5
WORKDIR /usr/bin/
RUN apk add --no-cache tzdata
COPY --from=buildEnv /go/src/fakeSDK/fakeSDK /usr/bin/fakeSDK

ENTRYPOINT [ "./fakeSDK" ]