version: '3'

services:
  token-auth:
    image: ${IMAGE_NAME}
    container_name: ${CONTAINER_NAME}
    logging:
      driver: json-file
      options:
        max-file: '10'
        max-size: 5M
    ports:
      - 8000:8080/tcp
    environment:
      - ADMIN_AUTH_MYSQL_URL=172.16.101.98:3306
      - ADMIN_AUTH_MYSQL_USER=root
      - ADMIN_AUTH_MYSQL_PASS=password
      - ADMIN_AUTH_MYSQL_DB=auth
      - ADMIN_AUTH_AUDIT_MYSQL_URL=172.16.101.98:3306
      - ADMIN_AUTH_AUDIT_MYSQL_USER=root
      - ADMIN_AUTH_AUDIT_MYSQL_PASS=password
      - ADMIN_AUTH_AUDIT_MYSQL_DB=emotibot
      - ADMIN_AUTH_PORT=8088
      - ADMIN_AUTH_TIMEOUT=86400
      - ADMIN_AUTH_SYSTEM_SECRET=emotibot_bfop_secret_key
    restart: always
